version: '3'
services:
  backend:
    build: './backend'
    ports:
      - "4000:80"
    volumes:
      - ./backend:/app

    depends_on:
      - db

  frontend:
    build: './frontend'
    ports:
      - "5000:80"
    volumes:
      - ./frontend:/usr/share/nginx/html

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - "3307:3306" 
